version: '3.3'
services:
  mysql:
    image: registry.mcs.psu.ac.th/mysql:latest
    container_name: dev_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1qa2ws3ed"
    ports:
      - "172.18.111.16:3306:3306"
    volumes:
      - /home/docker/mysql1/data:/var/lib/mysql
      
  phpmyadmin:
    depends_on:
      - mysql
    image: registry.mcs.psu.ac.th/phpmyadmin:latest
    container_name: "dev_phpmyadmin"
    restart: always
    ports:
      - 9090:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
